### ISSUE TITLE
拖拽视频报错

### ISSUE THREAD

**Issue by weiming7335** [Cc-Edit/CcClip#1]
runtime-core.esm-bundler.js:236 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at addTrack (TrackList.vue:186:5)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at HTMLDivElement.invoker (runtime-dom.esm-bundler.js:345:9)

**Comment by ReeCode** [comment]
您好，来信已收到，谢谢。

**Comment by Cc-Edit** [comment]
抱歉，我在本地无痕浏览器尝试复现这个bug，没有成功。 所以我只能对JSON.parse进行优化，[commit](https://github.com/Cc-Edit/CcClip/commit/740bc72a0e746e65cd439f337a3a015e79bf6512)

**Comment by Cc-Edit** [comment]
另外我做了一个简单的Bug Report模板，尝试按照模板简单的描述下复现路径，方便我定位问题。 tks~
